name: "e_sport_srv"
mode: "dev"
ip: "127.0.0.1"
port: ":8087"
start_time: "2022-06-01"
machine_id: 1

# 冒号后加空格
# 缩进是连续的两个空格
# 有兴趣的同学可以了解下toml
log:
  level: "debug"
  filename: "log/goods_srv.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "139.9.113.33"
  port: 3306
  user: "esports"
  password: "123"
  dbname: "esports"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "139.9.113.33"
  port: 6379
  password: ""
  db: 0
  pool_size: 100